### ISSUE TITLE
net.schmizz.sshj.common.LoggerFactory cannot be found

### ISSUE THREAD

**Issue by SirStone** [flathub/io.dbeaver.DBeaverCommunity#318]
I've just updated my Kubuntu system and dbeaver flatpak with it to "Version 25.1.2.202507061449"
<img width="720" height="87" alt="Image" src="https://github.com/user-attachments/assets/266ef164-4308-4b83-a60f-d8f6563a2868" />

Now when I try to create any SSH tunnel I get this error message
<img width="744" height="388" alt="Image" src="https://github.com/user-attachments/assets/81d1d614-73ca-4346-9afc-fc94114f93e7" />

Testing the SSH tunnel I get the same error but spelled slightly different
<img width="1041" height="649" alt="Image" src="https://github.com/user-attachments/assets/ca2b62be-9b32-46b1-b2d3-65c889be99ae" />

**Comment by rosenpapazov** [comment]
Same here, F42 

```
DBeaver Community - Free Universal Database Tool

          ID: io.dbeaver.DBeaverCommunity
         Ref: app/io.dbeaver.DBeaverCommunity/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 25.1.2
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 311.1 MB
     Runtime: org.gnome.Platform/x86_64/48
         Sdk: org.gnome.Sdk/x86_64/48

      Commit: f4e51cea137bd77153210778082fdb3d12516182460a6e42e48eafbc9cd8506e
      Parent: 228c73d84a5a1400acbd20477ad46a24757994c19be10c9e5f921756c0ccb3fe
     Subject: Merge pull request #317 from flathub/update-readme (bee29fbf907c)
        Date: 2025-07-10 09:18:00 +0000
```

**Comment by XhmikosR** [comment]
This is an upstream issue and should be fixed with v25.1.3.

**Comment by XhmikosR** [comment]
@Eonfge thanks! How long does it take for the update to be live?

**Comment by SirStone** [comment]
not fixed

<img width="1444" height="857" alt="Image" src="https://github.com/user-attachments/assets/6d92d5ee-8832-453e-be73-ea8ecfeaae4d" />

**Comment by XhmikosR** [comment]
Weird, the issue seems to be fixed for me.

**Comment by XhmikosR** [comment]
Scratch that, I had switched to JSch to work around the issue. Not sure if it's an upstream issue then...

**Comment by Eonfge** [comment]
Weird, I will need more information to reproduce this, so I can see what is going on. Never had this before when using an SSH tunnel

**Comment by pacrtn** [comment]
What information would you need ? 
From a bird's eye view it looks like some jdk deps shenanigans ? 

I don't think there is anything "special" about my setup or use but : 
I've been using this flatpak on Fedora (38-42) for a while. I'm using it with a work project that I keep on a separate git repo. 
When I set this one up I probably just git pulled and went on my merry way. And as stated in the original issue when 25.1.2 arrive and since (25.1.3, 25.1.4) the problem persists. I keep downgrading to 25.1.1 ( flatpak update --commit=a4955d0b2d1e309ad7423a2886b3117c09fff32aa751bb003c0c396c3a3360a1 io.dbeaver.DBeaverCommunity)
which works fine.

Using the same ssh profiles that follow along the project : 

<img width="679" height="676" alt="Image" src="https://github.com/user-attachments/assets/2650e095-7b62-45ad-9cfc-477fdaff0d67" />

**Comment by SirStone** [comment]
I could not find the time to do any test, but today I've updated again the flatpak to version 25.2.0 and the problem persist.

I'm starting think to drop it in favor for another tool. :(

**Comment by borfast** [comment]
Unfortunately, that's what I had to do. I already use Jetbrains' IDEs, so I started using the embedded database admin tool they all have. If I need something more, I might look at their DataGrip tool. I love DBeaver and frankly, I think I still prefer it, but I also need to work.
